service: mtgbot

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-north-1
  memorySize: 128
  timeout: 10

functions:
  handleEvent:
    handler: src/slack-event-handler.run
    events:
      - http:
          path: /
          method: post
  handleSqs:
    handler: src/sqs-handler.run
    reservedConcurrency: 1
